const ADD_FAVORITES = 'ADD_FAVORITES'
const DELETE_FAVORITES = 'DELETE_FAVORITES'
const FILTER = 'FILTER'
const ORDER = 'ORDER'
const DELETE_ALL = 'DELETE_ALL'
module.exports ={
    ADD_FAVORITES,
    DELETE_FAVORITES,
    FILTER,
    ORDER,
    DELETE_ALL
}